default:
  analysis title: ki-EEDBI-BGI
  counts:
    synID: syn23536851
    version:
    gene id: feature
  metadata:
    synID: syn23521999
    version: 4
    sample id: sampleId
  biomart:
    synID:
    version:
    filters: ensembl_gene_id
    host: ensembl.org
    organism: hsa
  factors: ["sampleId", "subjectId", "biopsyNumber", "testResult", "sex"]
  continuous: ["rin", "ageDays", "pct_pf_reads_aligned", "pct_coding_bases",
  "pct_intergenic_bases", "pct_intronic_bases", "ribosomal_bases"]
  x_var: biopsyNumber
  conditions:
    sex-diagnosis interaction:
    diagnosis:
    sex:
    another:
    condition3:
  sex check: sex
  dimensions:
    color: biopsyNumber
    shape: sex
    size: ageDays
  skip model: TRUE
  report: BGI-report
cchmc:
  analysis title: ki-EEDBI-CCHMC
  counts:
    synID: syn23353602
    version:
    gene id: feature
  metadata:
    synID: syn23538349
    version: 2
    sample id: subjectId
  biomart:
    synID:
    version:
    filters: ensembl_gene_id
    host: ensembl.org
    organism: hsa
  factors: ["subjectId", "diagnosis", "sex", "siteName", "biopsySite",
  "libraryPrepDate", "sequencingDate", "rnaIsolationDate"]
  continuous: ["ageDays", "pct_pf_reads_aligned", "pct_coding_bases",
  "pct_intergenic_bases", "pct_intronic_bases", "pct_ribosomal_bases"]
  x_var: diagnosis
  conditions:
    sex-diagnosis interaction:
    diagnosis:
    sex:
  sex check: sex
  dimensions:
    color: diagnosis
    shape: siteName
    size: ageDays
  skip model:
  report: CCHMC-report
uva:
  analysis title: ki-EEDBI-UVA
  counts:
    synID: syn23538555
    version: 2
    gene id: feature
  metadata:
    synID: syn23538559
    version: 2
    sample id: subjectId
  biomart:
    synID: syn23538559
    version:
    filters: ensembl_gene_id
    host: ensembl.org
    organism: hsa
  factors: ["subjectId", "diagnosis", "sex", "siteName", "biopsySite",
  "libraryPrepDate", "sequencingDate"]
  continuous: ["ageDays", "pct_pf_reads_aligned", "pct_coding_bases",
  "pct_intergenic_bases", "pct_intronic_bases"]
  x_var: diagnosis
  conditions:
    sex-diagnosis interaction:
    diagnosis:
    sex:
  sex check: sex
  dimensions:
    color: diagnosis
    shape: siteName
    size: ageDays
  skip model: TRUE
  report: UVA-report
